from __future__ import annotations
from typing import Protocol
from agent.contracts.lifecycle import CommandLifecycle, CommandState

class DurableCommandStatePort(Protocol):
    def insert(self, item: CommandLifecycle) -> None: ...
    def load(self, server_command_id: str) -> CommandLifecycle | None: ...
    def transition(self, server_command_id: str, state: CommandState) -> CommandLifecycle: ...
    def recovery_candidates(self) -> tuple[CommandLifecycle, ...]: ...
